<?php 

/**
 * Generated by "Guten Block Fields"
 * visit <https://github.com/emgk/guten-block-fields>
 */
function #component#_editor_scripts() {
    $editorStylePath = '#editorStylePath#';

    wp_enqueue_style(
      '#component#-blocks-editor-css',
      plugins_url($editorStylePath, __FILE__)
    );
}

// Hook scripts function into block editor hook
add_action( 'enqueue_block_editor_assets', '#component#_editor_scripts' );