const { Component } = wp.element;
const { InspectorControls } = wp.editor;
const { __ } = wp.i18n;
#import-packages#

/**
 * #ComponentName# Block InspectorControls class.
 * 
 * This Component was generated by Guten Block Fields 
 * https://github.com/emgk/guten-block-fields 
 * 
 * Add <#ComponentName#/> tag inside your block's edit function or 
 * visit https://wordpress.org/gutenberg/handbook/blocks/block-controls-toolbars-and-inspector/ for more information.  
 */
class #ComponentName# extends Component {
   
    /**
     * Constructor method.
     * 
     * @param {*} props 
     */
    constructor(props) {
        super(props);

        // @Todo: set state variables here.
    }

    /**
     * Render method.
     */
    render() {
        return (
            <InspectorControls>
                #fields#
            </InspectorControls>
        )
    }
}

// Export #ComponentName#
export default #ComponentName#;