/* 
CSS generated by "Guten Block field". 
*/
.components-panel__body .gbf-#component#-panel{
    border-bottom: 1px solid #e2e4e7;
}

.components-panel__body .gbf-#component#-panel .components-base-control__field,
.gbf-#component#-control .components-base-control__field{
    width: 100%;
}

.gbf-#component#-control .components-text-control__input,
.gbf-#component#-control .components-select-control__input{
    display: inline-block;
    width: 100%;
    max-width: 100%;
    line-height: 21px;
    background: inherit;
    font-size: 13px;
    color: #23282d;
    box-shadow: none;
}

.gbf-#component#-control .components-base-control {
    margin-bottom: 0px !important;
}